---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore, Gemfile. Gemfile.lock]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Bobzon for Amazon - Price Drop Tracker"
keywords:    "bobzon, amazon, manager, tracker, follow, drop, price, cheap, discount, deals"
description: "Get always the best price in Amazon with Bobzon Price Tracker! Download it FREE NOW!"
google_analytics_key: UA-25289053-11 ## put YOUR key here to enable tracking! (blank to disable)
appstore_link: "https://itunes.apple.com/app/bobzon-for-amazon/id1206419148?ct=web&mt=8&at=1000lom5"
googleplay_link: "https://play.google.com/store/apps/details?id=com.bobgoo.bobzon"

url: https://bobzon.bobgoo.com
enforce_ssl: bobzon.bobgoo.com

twitter:
    username: "@BobzonApp"

defaults:
  -
    scope:
        path: ""
    values:
        image:
            #path: /img/Icon-Rounded-256.png
            twitter: /img/FBBanner.png
            facebook: /img/FBBanner.png
            height: 630
            width: 1200

  
### template colors, used site-wide via css ###
colors:
  red:       '#5A5151'      
  black:     '#111111'
  white:     '#f8f8f8'
  mainblue:  '#146EB4'
  faceblue:  '#3B5998'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  gtgold:    '#E0A01F'
  gtnavy:    '#01192F'
  gtmetallic: '#A08452'

kramdown:
  auto_ids:  false

gems:
  - jekyll-seo-tag
